from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime


def generate_filled_pdf(
    form_fields: list,
    filled_answers: dict,
    document_checklist: dict,
    output_path: str = "filled_form.pdf"
) -> str:

    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        rightMargin=2*cm,
        leftMargin=2*cm,
        topMargin=2*cm,
        bottomMargin=2*cm
    )

    styles = getSampleStyleSheet()
    story = []

    # ── Styles ────────────────────────────────
    title_style = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontSize=18,
        textColor=colors.HexColor("#1a3c5e"),
        spaceAfter=6,
        alignment=TA_CENTER
    )
    sub_style = ParagraphStyle(
        "Sub",
        parent=styles["Normal"],
        fontSize=9,
        textColor=colors.grey,
        alignment=TA_CENTER,
        spaceAfter=16
    )
    label_style = ParagraphStyle(
        "Label",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.grey,
        spaceBefore=8
    )
    value_style = ParagraphStyle(
        "Value",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.black,
        spaceAfter=4
    )
    section_style = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#1a3c5e"),
        spaceBefore=16,
        spaceAfter=8
    )

    # ── Header ────────────────────────────────
    story.append(Paragraph("FILLED GOVERNMENT FORM", title_style))
    story.append(Paragraph(
        f"Generated by CiviGuide AI — {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        sub_style
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a3c5e")))
    story.append(Spacer(1, 0.4*cm))

    # ── Filled Fields ─────────────────────────
    story.append(Paragraph("APPLICANT INFORMATION", section_style))

    for field in form_fields:
        field_name = field.get("field", "")
        label = field.get("label", field_name.replace("_", " ").title())
        value = filled_answers.get(field_name, "— Not provided —")
        if value is None or value == "":
            value = "— Not provided —"

        story.append(Paragraph(label.upper(), label_style))
        story.append(Paragraph(str(value), value_style))
        story.append(HRFlowable(width="100%", thickness=0.3, color=colors.lightgrey))

    story.append(Spacer(1, 0.6*cm))

    # ── Document Checklist ────────────────────
    story.append(Paragraph("REQUIRED DOCUMENTS CHECKLIST", section_style))

    if document_checklist.get("summary"):
        story.append(Paragraph(document_checklist["summary"], styles["Normal"]))
        story.append(Spacer(1, 0.3*cm))

    docs = document_checklist.get("required_documents", [])
    if docs:
        table_data = [["#", "Document", "Status", "Notes"]]
        for i, doc in enumerate(docs, 1):
            status = "MANDATORY" if doc.get("mandatory") else "OPTIONAL"
            table_data.append([
                str(i),
                doc.get("name", ""),
                status,
                doc.get("reason", "")
            ])

        table = Table(table_data, colWidths=[1*cm, 4.5*cm, 2.5*cm, 8*cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a3c5e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("FONTSIZE", (0, 1), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8fc")]),
            ("GRID", (0, 0), (-1, -1), 0.3, colors.lightgrey),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ]))
        story.append(table)

    # ── Tips ──────────────────────────────────
    tips = document_checklist.get("tips", [])
    if tips:
        story.append(Spacer(1, 0.4*cm))
        story.append(Paragraph("SUBMISSION TIPS", section_style))
        for tip in tips:
            story.append(Paragraph(f"• {tip}", styles["Normal"]))

    # ── Processing Time ───────────────────────
    eta = document_checklist.get("estimated_processing_time")
    if eta:
        story.append(Spacer(1, 0.3*cm))
        story.append(Paragraph(
            f"Estimated Processing Time: {eta}",
            ParagraphStyle("ETA", parent=styles["Normal"],
                           textColor=colors.HexColor("#1a3c5e"),
                           fontName="Helvetica-Bold")
        ))

    # ── Footer ────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey))
    story.append(Paragraph(
        "This document was generated by CiviGuide AI. Please verify all information before submission.",
        ParagraphStyle("Footer", parent=styles["Normal"],
                       fontSize=7, textColor=colors.grey, alignment=TA_CENTER)
    ))

    doc.build(story)
    return output_path
