import PDFDocument from "pdfkit";
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const CM = 28.3465;
const NAVY = "#1a3c5e";
const GREY = "#808080";
const LIGHT_GREY = "#d3d3d3";
const ROW_ALT = "#f5f8fc";

/*
 * Fonts: pdfkit's built-in Helvetica only covers WinAnsi, so "₹" and Indian names came out
 * as garbage. We embed Noto Sans (Latin, ₹) and Noto Sans Devanagari (Hindi, Marathi, …),
 * both under the SIL Open Font License (assets/fonts/OFL.txt). Noto Sans Devanagari has no
 * Latin letters, so text is split into script runs and each run uses the font that covers it.
 *
 * Other Indic scripts (Tamil, Bengali, Gujarati, …) are not bundled and render as empty boxes;
 * to support one, add its Noto font here and extend scriptRuns().
 */
const FONT_DIR = fileURLToPath(new URL("../assets/fonts/", import.meta.url));
const FONTS = {
  latin: `${FONT_DIR}NotoSans-Regular.ttf`,
  latinBold: `${FONT_DIR}NotoSans-Bold.ttf`,
  deva: `${FONT_DIR}NotoSansDevanagari-Regular.ttf`,
  devaBold: `${FONT_DIR}NotoSansDevanagari-Bold.ttf`,
};

const DEVANAGARI = /[ऀ-ॿ꣠-ꣿ᳐-᳿]/;
// Characters both fonts have: they stay in whichever run they're in, so "₹20,000 रमेश" doesn't fragment.
const SHARED = /[\s0-9.,:;!?()\-/₹"'–—%+]/;

/** Split text into [{ deva, text }] runs by script. */
export function scriptRuns(text) {
  const runs = [];
  for (const ch of String(text)) {
    const deva = DEVANAGARI.test(ch) ? true : SHARED.test(ch) ? runs.at(-1)?.deva ?? false : false;
    const last = runs.at(-1);
    if (last && last.deva === deva) last.text += ch;
    else runs.push({ deva, text: ch });
  }
  return runs;
}

const fontFor = (deva, bold) => (deva ? (bold ? "deva-bold" : "deva") : bold ? "latin-bold" : "latin");

function registerFonts(doc) {
  doc.registerFont("latin", FONTS.latin);
  doc.registerFont("latin-bold", FONTS.latinBold);
  doc.registerFont("deva", FONTS.deva);
  doc.registerFont("deva-bold", FONTS.devaBold);
}

/** Write text that may mix scripts, switching font per run. `x`/`y` as for doc.text(). */
function mixedText(doc, text, { bold = false, x, y, ...opts } = {}) {
  const runs = scriptRuns(text);
  if (!runs.length) runs.push({ deva: false, text: "" });
  runs.forEach((run, i) => {
    doc.font(fontFor(run.deva, bold));
    const options = { ...opts, continued: i < runs.length - 1 };
    if (i === 0) doc.text(run.text, x, y, options);
    else doc.text(run.text, options);
  });
}

/** Height of mixed-script text: measured in both fonts and the larger taken, so cells never overflow. */
function mixedHeight(doc, text, { bold = false, ...opts } = {}) {
  const s = String(text);
  const latin = doc.font(fontFor(false, bold)).heightOfString(s, opts);
  if (!DEVANAGARI.test(s)) return latin;
  return Math.max(latin, doc.font(fontFor(true, bold)).heightOfString(s, opts));
}

const asText = (v) => (typeof v === "string" ? v : v === null || v === undefined ? "" : String(v));

/** Build the filled-form PDF and resolve with its bytes. */
export function generateFilledPDF(formFields, filledAnswers, documentChecklist) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 2 * CM });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    try {
      registerFonts(doc);
      render(doc, formFields, filledAnswers, documentChecklist);
      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function render(doc, formFields, filledAnswers, documentChecklist) {
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;

  const hr = (thickness, color) => {
    const y = doc.y;
    doc.save().moveTo(left, y).lineTo(left + width, y)
      .lineWidth(thickness).strokeColor(color).stroke().restore();
    doc.moveDown(0.3);
  };
  const section = (title) => {
    doc.moveDown(1);
    doc.fontSize(12).fillColor(NAVY);
    mixedText(doc, title, { bold: true, x: left, y: doc.y, width });
    doc.moveDown(0.5);
  };
  const normal = (text, opts = {}) => {
    doc.fontSize(10).fillColor("black");
    mixedText(doc, text, { x: left, y: doc.y, width, ...opts });
  };

  // ── Header ────────────────────────────────
  doc.fontSize(18).fillColor(NAVY);
  mixedText(doc, "FILLED GOVERNMENT FORM", { bold: true, align: "center", width });
  doc.moveDown(0.3);
  const now = new Date().toLocaleString("en-US", {
    month: "long", day: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: true,
  });
  doc.fontSize(9).fillColor(GREY);
  mixedText(doc, `Generated by CiviGuide AI — ${now}`, { align: "center", width });
  doc.moveDown(1);
  hr(1, NAVY);

  // ── Filled Fields ─────────────────────────
  section("APPLICANT INFORMATION");
  for (const field of formFields) {
    const name = asText(field.field);
    const label = asText(field.label) || name.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
    let value = filledAnswers[name];
    if (value === null || value === undefined || value === "") value = "— Not provided —";
    else if (value === true) value = "Yes";
    else if (value === false) value = "No";
    else if (typeof value === "object") value = JSON.stringify(value);

    doc.moveDown(0.4);
    doc.fontSize(8).fillColor(GREY);
    mixedText(doc, label.toUpperCase(), { x: left, y: doc.y, width });
    doc.fontSize(11).fillColor("black");
    mixedText(doc, String(value), { x: left, y: doc.y, width });
    doc.moveDown(0.2);
    hr(0.3, LIGHT_GREY);
  }

  // ── Document Checklist ────────────────────
  doc.moveDown(0.5);
  section("REQUIRED DOCUMENTS CHECKLIST");

  if (documentChecklist.summary) {
    normal(asText(documentChecklist.summary));
    doc.moveDown(0.5);
  }

  const docs = Array.isArray(documentChecklist.required_documents)
    ? documentChecklist.required_documents.filter((d) => d && typeof d === "object")
    : [];
  if (docs.length) {
    const colWidths = [1 * CM, 4.5 * CM, 2.5 * CM, 8 * CM];
    const pad = 6;
    const rows = [
      ["#", "Document", "Status", "Notes"],
      ...docs.map((d, i) => {
        const ready = d.ready || d.attached_file;
        return [
          String(i + 1),
          asText(d.name),
          (d.mandatory ? "MANDATORY" : "OPTIONAL") + (ready ? "\nREADY" : ""),
          asText(d.reason) + (d.attached_file ? `\nFile noted: ${asText(d.attached_file)}` : ""),
        ];
      }),
    ];

    rows.forEach((row, r) => {
      const isHeader = r === 0;
      doc.fontSize(isHeader ? 9 : 8);
      const rowHeight = Math.max(...row.map((cell, c) =>
        mixedHeight(doc, cell, { bold: isHeader, width: colWidths[c] - 2 * pad }))) + 2 * pad;

      if (doc.y + rowHeight > doc.page.height - doc.page.margins.bottom) doc.addPage();
      const y = doc.y;

      let x = left;
      row.forEach((cell, c) => {
        const fill = isHeader ? NAVY : r % 2 === 1 ? "white" : ROW_ALT;
        doc.save().rect(x, y, colWidths[c], rowHeight).fillAndStroke(fill, LIGHT_GREY).restore();
        doc.fillColor(isHeader ? "white" : "black");
        mixedText(doc, cell, { bold: isHeader, x: x + pad, y: y + pad, width: colWidths[c] - 2 * pad });
        x += colWidths[c];
      });
      doc.x = left;
      doc.y = y + rowHeight;
    });
  }

  // ── Tips ──────────────────────────────────
  const tips = Array.isArray(documentChecklist.tips) ? documentChecklist.tips : [];
  if (tips.length) {
    doc.moveDown(0.5);
    section("SUBMISSION TIPS");
    for (const tip of tips) normal(`• ${asText(tip)}`);
  }

  // ── Processing Time ───────────────────────
  const eta = documentChecklist.estimated_processing_time;
  if (eta) {
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor(NAVY);
    mixedText(doc, `Estimated Processing Time: ${asText(eta)}`, { bold: true, x: left, y: doc.y, width });
  }

  // ── Footer ────────────────────────────────
  doc.moveDown(2);
  hr(0.5, LIGHT_GREY);
  doc.fontSize(7).fillColor(GREY);
  mixedText(doc,
    "This document was generated by CiviGuide AI. Please verify all information before submission.",
    { x: left, y: doc.y, align: "center", width });
}

/** Build the filled-form PDF and write it to `outputPath`. */
export async function writeFilledPDF(formFields, filledAnswers, documentChecklist, outputPath = "filled_form.pdf") {
  await writeFile(outputPath, await generateFilledPDF(formFields, filledAnswers, documentChecklist));
  return outputPath;
}
