import PDFDocument from "pdfkit";
import { writeFile } from "node:fs/promises";

const CM = 28.3465;
const NAVY = "#1a3c5e";
const GREY = "#808080";
const LIGHT_GREY = "#d3d3d3";
const ROW_ALT = "#f5f8fc";

/** Build the filled-form PDF and resolve with its bytes. */
export function generateFilledPDF(formFields, filledAnswers, documentChecklist) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 2 * CM });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const left = doc.page.margins.left;
    const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;

    const hr = (thickness, color) => {
      const y = doc.y;
      doc.save().moveTo(left, y).lineTo(left + width, y)
        .lineWidth(thickness).strokeColor(color).stroke().restore();
      doc.moveDown(0.3);
    };
    const section = (title) => {
      doc.moveDown(1);
      doc.font("Helvetica-Bold").fontSize(12).fillColor(NAVY).text(title, left, doc.y, { width });
      doc.moveDown(0.5);
    };
    const normal = (text, opts = {}) =>
      doc.font("Helvetica").fontSize(10).fillColor("black").text(text, left, doc.y, { width, ...opts });

    // ── Header ────────────────────────────────
    doc.font("Helvetica-Bold").fontSize(18).fillColor(NAVY)
      .text("FILLED GOVERNMENT FORM", { align: "center", width });
    doc.moveDown(0.3);
    const now = new Date().toLocaleString("en-US", {
      month: "long", day: "2-digit", year: "numeric", hour: "2-digit", minute: "2-digit", hour12: true,
    });
    doc.font("Helvetica").fontSize(9).fillColor(GREY)
      .text(`Generated by CiviGuide AI — ${now}`, { align: "center", width });
    doc.moveDown(1);
    hr(1, NAVY);

    // ── Filled Fields ─────────────────────────
    section("APPLICANT INFORMATION");
    for (const field of formFields) {
      const name = field.field ?? "";
      const label = field.label ?? name.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
      let value = filledAnswers[name];
      if (value === null || value === undefined || value === "") value = "— Not provided —";

      doc.moveDown(0.4);
      doc.font("Helvetica").fontSize(8).fillColor(GREY).text(label.toUpperCase(), left, doc.y, { width });
      doc.font("Helvetica").fontSize(11).fillColor("black").text(String(value), left, doc.y, { width });
      doc.moveDown(0.2);
      hr(0.3, LIGHT_GREY);
    }

    // ── Document Checklist ────────────────────
    doc.moveDown(0.5);
    section("REQUIRED DOCUMENTS CHECKLIST");

    if (documentChecklist.summary) {
      normal(documentChecklist.summary);
      doc.moveDown(0.5);
    }

    const docs = documentChecklist.required_documents ?? [];
    if (docs.length) {
      const colWidths = [1 * CM, 4.5 * CM, 2.5 * CM, 8 * CM];
      const pad = 6;
      const rows = [
        ["#", "Document", "Status", "Notes"],
        ...docs.map((d, i) => [
          String(i + 1),
          d.name ?? "",
          (d.mandatory ? "MANDATORY" : "OPTIONAL") + (d.attached_file ? "\nATTACHED" : ""),
          (d.reason ?? "") + (d.attached_file ? `\nAttached: ${d.attached_file}` : ""),
        ]),
      ];

      rows.forEach((row, r) => {
        const isHeader = r === 0;
        doc.font(isHeader ? "Helvetica-Bold" : "Helvetica").fontSize(isHeader ? 9 : 8);
        const rowHeight = Math.max(...row.map((cell, c) =>
          doc.heightOfString(cell, { width: colWidths[c] - 2 * pad }))) + 2 * pad;

        if (doc.y + rowHeight > doc.page.height - doc.page.margins.bottom) doc.addPage();
        const y = doc.y;

        let x = left;
        row.forEach((cell, c) => {
          const fill = isHeader ? NAVY : r % 2 === 1 ? "white" : ROW_ALT;
          doc.save().rect(x, y, colWidths[c], rowHeight).fillAndStroke(fill, LIGHT_GREY).restore();
          doc.fillColor(isHeader ? "white" : "black")
            .text(cell, x + pad, y + pad, { width: colWidths[c] - 2 * pad });
          x += colWidths[c];
        });
        doc.x = left;
        doc.y = y + rowHeight;
      });
    }

    // ── Tips ──────────────────────────────────
    const tips = documentChecklist.tips ?? [];
    if (tips.length) {
      doc.moveDown(0.5);
      section("SUBMISSION TIPS");
      for (const tip of tips) normal(`• ${tip}`);
    }

    // ── Processing Time ───────────────────────
    const eta = documentChecklist.estimated_processing_time;
    if (eta) {
      doc.moveDown(0.5);
      doc.font("Helvetica-Bold").fontSize(10).fillColor(NAVY)
        .text(`Estimated Processing Time: ${eta}`, left, doc.y, { width });
    }

    // ── Footer ────────────────────────────────
    doc.moveDown(2);
    hr(0.5, LIGHT_GREY);
    doc.font("Helvetica").fontSize(7).fillColor(GREY).text(
      "This document was generated by CiviGuide AI. Please verify all information before submission.",
      left, doc.y, { align: "center", width },
    );

    doc.end();
  });
}

/** Build the filled-form PDF and write it to `outputPath`. */
export async function writeFilledPDF(formFields, filledAnswers, documentChecklist, outputPath = "filled_form.pdf") {
  await writeFile(outputPath, await generateFilledPDF(formFields, filledAnswers, documentChecklist));
  return outputPath;
}
